# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bloomberg pybossa-default-theme CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository and submodules recursively
      uses: actions/checkout@v4
      with:
        submodules: recursive
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: static/src/yarn.lock
    - name: Pre setup
      run: |
        TASK_PRESENTER_VERSION=$(node -p "require('./package.json').dependencies['@dtwebservices/task-presenter-components']")
        npm install https://s3.amazonaws.com/cf-s3uploads/pybv/${TASK_PRESENTER_VERSION}/task-presenter-components.tgz
      working-directory: static/src
    - name: Build (webpack)
      env:
        NODE_OPTIONS: --openssl-legacy-provider
      run: yarn webpack
      working-directory: static/src
    - run: yarn test
      working-directory: static/src
    - run: yarn lint
      working-directory: static/src
